services:
  mongodb:
    image: mongo:7
    container_name: mongodb_container
    ports:
      - 27017:27017
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog_container
  bukwarkauth:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - mailhog
    ports:
      - 8080:8080
    container_name: bulwarkauth_container

